-- Patch for multi-user, quota, permissions, storage config
ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'user';
ALTER TABLE users ADD COLUMN IF NOT EXISTS quota_gb INT NOT NULL DEFAULT 10;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar VARCHAR(255) NULL;

CREATE TABLE IF NOT EXISTS storage_configs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provider VARCHAR(30) NOT NULL UNIQUE,
  config_json TEXT NULL,
  is_active TINYINT NOT NULL DEFAULT 0,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_permissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  can_upload TINYINT NOT NULL DEFAULT 1,
  can_download TINYINT NOT NULL DEFAULT 1,
  can_share TINYINT NOT NULL DEFAULT 1,
  can_delete TINYINT NOT NULL DEFAULT 0,
  can_create_folder TINYINT NOT NULL DEFAULT 1,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
